apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher-backup-crd
  namespace: cattle-resources-system
spec:
  interval: 5m
  chart:
    spec:
      chart: rancher-backup-crd
      version: '1.0.301'
      sourceRef:
        kind: HelmRepository
        name: rancher-charts
        namespace: flux-system
      interval: 1m



